### ISSUE TITLE
能不能换一个图标

### ISSUE THREAD

**Issue by chenbaker** [lurenjia534/notification-notification#1]
能不能换一个图标，太像微信了，总以为有微信信息

**Comment by lurenjia534** [comment]
The push icon will be replaced today

**Comment by lurenjia534** [comment]
> 能不能换一个图标，太像微信了，总以为有微信信息

The push icon will be replaced today

**Comment by lurenjia534** [comment]
> 能不能换一个图标，太像微信了，总以为有微信信息
The problem is solved and the Issues will be closed
